# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx6500m

group=noobanidus.mods.toofast
version=0.4.3.6

mod_name=TooFast
mod_author=Noobanidus
mod_id=toofast
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/too-fast
mod_source=https://github.com/noobanidus/toofast
mod_issues=https://github.com/noobanidus/toofast/issues
mod_description=Allows players to move quickly.
mod_license=mit
mixin_id=toofast

# ForgeGradle properties (gradle/forge.gradle)
minecraft_version=1.21.0
neo_version=21.0.167
minecraft_version_range=[1.21)
neo_version_range=[21.0,)
loader_version_range=[2,)

forge_at=src/main/resources/META-INF/accesstransformer.cfg



# CurseForge properties (gradle/curseforge.gradle)
curse_project=550678
curse_page=https://www.curseforge.com/minecraft/mc-mods/too-fast
curse_release_type=release
curse_versions=1.21, 1.21.1

# Are we running on Jenkins?
java_21=true

git_previous_commit=d1fe8af533aeb577c6db763de83cbfde7e7cd2b1
