org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.jvmargs=-Xmx6500m

minecraft_version=26.1
minecraft_version_range=[26.1,)
java_version=25

neoform_version=26.1-1
mod_id=toofast
mod_version=0.5.4.7

fabric_loader_version=0.18.5
fabric_api_version=0.144.3+26.1

# NeoForge
neoforge_version=26.1.0.2-beta
neoforge_version_range=[26.1.0.2-beta,)

# Libraries
mixin_version=0.15.4+mixin.0.8.7
asm_version=9.7

mod_group_id=noobanidus.mods
mod_name=Too Fast
mod_description=Disables 'moved too quickly'.
sources_url=https://github.com/noobanidus/toofast
issues_url=https://github.com/noobanidus/toofast/issues
license_url=https://github.com/noobanidus/toofast/tree/master
homepage_url=https://www.curseforge.com/minecraft/mc-mods/too-fast

curseforge_id=550678
modrinth_id=w6JSkKSH
maven_group=noobanidus.mods

git_previous_commit=093fdf23a4efa5eb4f2551b8d2950786043be5af
